### ISSUE TITLE
Add custom data for users and items

### ISSUE THREAD

**Issue by marcellov7** [ankane/disco-php#2]
Hello,
this is really an awesome library for php.
There i a way to add custom data to users and items to consider them into the recommendation system? 

Example:
```
user_id : 1,
   gender: "m",
   age: 30,
   ..
```

Would be useful to set a weight too.
Thank you

**Comment by ankane** [comment]
Hey @marcellov7, side information and weights aren't currently supported. It would require switching matrix factorization libraries, so it's not something I'm planning to do right now.

**Comment by marcellov7** [comment]
Hey @ankane, thanks for your reply,
Is there any library you can recommend to do this? Maybe I'll try to contribute.

**Comment by ankane** [comment]
[cmfrec](https://github.com/david-cortes/cmfrec) supports side information as well as weights for implicit feedback. I created a [Ruby library](https://github.com/ankane/cmfrec-ruby) for it that someone could probably port, but think it'd be better as a separate project.
