### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ehsanquddusi** [ankane/disco-php#3]
The library looks great. 

It would be nice to integrate saving/loading of recommendations into some storage/database. Like integrating `pgvector/pgvector-php` with this package for storing the recommendations.

We may have additional methods like 
```php
$recommender->itemRecs($itemId)->save();
$recommender->itemRecs($itemId)->refresh();
$recommender->itemRecs($itemId)->delete();
$recommender->itemRecs($itemId)->get();
```
Additionally, `$recommender->itemRecs($itemId)` may check for recommendations existance in database and load the same instead of generating new recommendations. The user may call `$recommender->itemRecs($itemId)->refresh()` to make new recommendations and sync them to database.

Maybe use model observers / events to refresh the recommendations automatically on model creation / updation or deletion.

**Comment by ankane** [comment]
Hi @ehsanquddusi, thanks for the suggestion. I'd like to keep the storage separate, but there's an example in the readme for [pgvector](https://github.com/pgvector/pgvector-php/blob/master/examples/disco/example.php).
